# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: pwd
      run: ls -a target
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 3.109.139.52
        username: ubuntu
        port: 22
        key: ${{ secrets.KEY }}
        source: "/home/runner/work/code/code/target/demo-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/"
        
    - name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v1
      uses: qoqa/action-s3-cp@v1.1
      env:
        AWS_DEFAULT_REGION: ap-south-1
        AWS_S3_BUCKET: buc121
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_REGION: ap-south-1
        AWS_S3_PATH: '/home/runner/work/code/code/target/demo-0.0.1-SNAPSHOT.jar'
        FILE: './demo-0.0.1-SNAPSHOT.jar'
