# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
              
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 13.232.243.70
        username: root
        port: 22
        key: ${{ secrets.Key }}
        source: "/home/runner/work/code/code/target/demo-0.0.1-SNAPSHOT.jar,github-service"
        target: "/home/ubuntu/"
      
    - name: ls -a via ssh
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: |
             sudo systemctl stop github.service 
             sudo mv /home/ubuntu/github-service /etc/systemd/system/github.service
             sudo systemctl deamon-reload
             sudo systemctl start github
             sudo mkdir -p /home/ubuntu/backup
             sudo cp "/home/ubuntu/github/workspace/target/demo-0.0.1-SNAPSHOT.jar" "/home/ubuntu/backup/demo-0.0.1-SNAPSHOT.jar-$(date +"%Y.%m.%d.%H.%M.%S")"
             sudo apt-get install zip
             sudo zip -r jarfile.zip backup/
        host: 13.232.243.70
        user: root
        key: ${{ secrets.key}} 
